spring.datasource.url=jdbc:postgresql://dpg-cro3vru8ii6s73f2hpkg-a.oregon-postgres.render.com/booksql
spring.datasource.username=booksql_user
spring.datasource.password=wR8qhfoh7zDbXPrOFI1Bp7Oa4VizNADv
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.show-sql=true
logging.level,org.hibernate.SQL=DEBUG