spring.datasource.url=jdbc:postgresql://dpg-crq25ftds78s73d6jli0-a.oregon-postgres.render.com/books_lir7
spring.datasource.username=books_lir7
spring.datasource.password=FEJnlnOOTG0dMSpLTXpyLKVm8EyAtewS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.show-sql=true
logging.level,org.hibernate.SQL=DEBUG
